name: "Auto update ips"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
env:
  TZ: Asia/Shanghai


jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Get IPS
        run: |
          echo Update ip.txt
          curl -s https://www.baipiao.eu.org/cloudflare/ips-v4 -o ${GITHUB_WORKSPACE}/ip.txt
          echo Update ipv6.txt
          curl -s https://www.baipiao.eu.org/cloudflare/ips-v6 -o ${GITHUB_WORKSPACE}/ipv6.txt
      - name: Apply ips changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
         commit_message: Apply ips changes
