name: "Auto update ips"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
env:
  TZ: Asia/Shanghai


jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Get IPS
        run: |
          curl -s https://www.baipiao.eu.org/cloudflare/ips-v4 -o ip.txt
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: update ip.txt
