name: "Auto Update IP"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"
env:
  TZ: Asia/Shanghai


jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Get IP
        run: |
          echo Get ip.txt
          curl -s https://www.baipiao.eu.org/cloudflare/ips-v4 -o ${GITHUB_WORKSPACE}/ip.txt
          echo Get ipv6.txt
          curl -s https://www.baipiao.eu.org/cloudflare/ips-v6 -o ${GITHUB_WORKSPACE}/ipv6.txt
      - name: Apply IP Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
         commit_message: Apply IP Changes
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 0
          keep_minimum_runs: 1
